# now run the containers together `docker-compose up`
# docker-compose may fail if you don't initialize the database

db:
   build: database
   environment:
       - MYSQL_ROOT_PASSWORD=pass
   volumes:
      # storage for the database (needs to be initialized first)
       - ./database/storage:/var/lib/mysql

app:
    build: .
    links:
        - db
    ports:
        - "8081:8081"
    volumes:
      # folder with frontend static files
        - ./dist:/app/dist
      # folder for backend sources
      # (not required to run the app since it is also inside the container itself)
      #  - ./api:/app/api

nginx:
    build: nginx
    links:
      - app
    ports:
      - "80:80"